[package]
name = "afterparty"
version = "0.1.2"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A github webhook server"
documentation = "http://softprops.github.io/afterparty"
homepage = "https://github.com/softprops/afterparty"
repository = "https://github.com/softprops/afterparty"
keywords = ["github", "ci", "webhook", "hyper"]
license = "MIT"
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"
serde_json = "0.8"
glob = "0.2.11"


[dev-dependencies]
env_logger = "0.3"

[dependencies]
hex = "0.2.0"
case = "0.0"
hyper = "0.10"
rust-crypto = "0.2"
log = "0.3"
env_logger = "0.3"
serde = "0.8"
serde_json = "0.8"
